version: '3.8'

services:
  mcp-server-host:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-server-host:latest
    container_name: mcp-server-host
    restart: unless-stopped
    networks:
      docker-network:
        ipv4_address: 172.18.0.15
    volumes:
      - /mnt/docker-data/volumes/mcp-workspace:/workspace:rw
      - /mnt/docker-data/volumes/mcp-data:/app/data:rw
      - /mnt/docker-data/volumes/mcp-logs:/var/log:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./config:/app/config:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WORKSPACE_PATH=/workspace
      - MCP_SERVERS_CONFIG=/app/config/servers.json
    ports:
      - "8080:8080"  # Optional: for web-based MCP servers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "/app/scripts/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  docker-network:
    external: true
    name: docker-network